# Generated by Django 5.0.3 on 2024-04-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_data_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('NID', models.IntegerField(max_length=17)),
                ('Address', models.CharField(max_length=100)),
                ('SSCDiv', models.CharField(max_length=10)),
                ('SSCyr', models.IntegerField(max_length=10)),
                ('SSCres', models.FloatField(max_length=4)),
                ('SSCinst', models.CharField(max_length=100)),
                ('HSCDiv', models.CharField(max_length=10)),
                ('HSCyr', models.IntegerField(max_length=10)),
                ('HSCres', models.FloatField(max_length=4)),
                ('HSCinst', models.CharField(max_length=100)),
                ('UNDRsub', models.CharField(max_length=100, null=True)),
                ('UNDRyr', models.IntegerField(max_length=10, null=True)),
                ('UNDRres', models.FloatField(max_length=4, null=True)),
                ('UNDRinst', models.CharField(max_length=100, null=True)),
            ],
        ),
       migrations.DeleteModel(
           name='Item',
       ),
    ]
