# Generated by Django 5.0.3 on 2024-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_tutorreg_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorreg2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('NID', models.IntegerField()),
                ('primary', models.CharField(max_length=10)),
                ('junior_secondary', models.CharField(max_length=10)),
                ('secondary', models.CharField(max_length=10)),
                ('hsc', models.CharField(max_length=10)),
                ('undergrade', models.CharField(max_length=10)),
                ('postgrade', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=15)),
                ('experiance', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
