# Generated by Django 5.0.3 on 2024-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_addtutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=100)),
                ('tcrname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
