# Generated by Django 5.0.3 on 2024-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('stdname', models.CharField(max_length=100)),
                ('tcrname', models.CharField(max_length=100)),
                ('attendence', models.IntegerField()),
            ],
        ),
    ]
