# Generated by Django 5.0.3 on 2024-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_notification1'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtutor',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
