# Generated by Django 5.0.3 on 2024-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_addtutor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification1',
            name='stdname_last',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
