# Generated by Django 5.0.3 on 2024-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_notification1_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification1',
            name='Area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
