# Generated by Django 5.0.3 on 2024-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_notification1_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaltutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('stdname', models.CharField(max_length=100)),
                ('tchrname', models.CharField(max_length=100)),
                ('Starting_Date', models.DateField()),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
