# Generated by Django 5.0.3 on 2024-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_personaltutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltutor',
            name='subject',
        ),
    ]
